In [53]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.decomposition import  LatentDirichletAllocation
import pickle

In [55]:
with open("topic_modelling.pickle", "rb") as f:
    pickle_data = pickle.load(f)
data = pickle_data["data"]

In [65]:
tf_vectorizer = CountVectorizer(max_df=0.90, 
                                min_df=0.05,
                                max_features=100000,                               
                                ngram_range=(1,2),
                                stop_words='english')

In [67]:
dtm_tf = tf_vectorizer.fit_transform(data)

In [68]:
lda = LatentDirichletAllocation(n_topics=5, max_iter=500,
                                learning_method='online',
                                n_jobs=-1,
                                learning_offset=50.,
                                random_state=0)

In [69]:
lda.fit(dtm_tf)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7,
             learning_method='online', learning_offset=50.0,
             max_doc_update_iter=100, max_iter=500, mean_change_tol=0.001,
             n_jobs=-1, n_topics=5, perp_tol=0.1, random_state=0,
             topic_word_prior=None, total_samples=1000000.0, verbose=0)

In [75]:
from sklearn.externals import joblib
joblib.dump(lda, 'topic_modeling_sklearn.pkl')

['topic_modeling_sklearn.pkl']

In [76]:
clf = joblib.load('topic_modeling_sklearn.pkl') 

In [70]:
tf_feature_names = tf_vectorizer.get_feature_names()
#print_top_words(lda, tf_feature_names, 12)

In [71]:
#for i in range(len(file_details)):
#for i in range(5):
#    print(file_details[i], lda.transform(dtm_tf[i]))

In [72]:
import pyLDAvis
import pyLDAvis.sklearn
pyLDAvis.enable_notebook()

In [77]:
pyLDAvis.sklearn.prepare(clf, dtm_tf, tf_vectorizer, mds='mmds')

PreparedData(topic_coordinates=            Freq  cluster  topics         x         y
topic                                                
2      54.667926        1       1 -0.012972  0.148861
1      38.112405        1       2  0.035833  0.094067
0       4.255031        1       3 -0.307137 -0.131701
4       2.901172        1       4  0.149021 -0.258543
3       0.063466        1       5  0.135255  0.147315, topic_info=     Category         Freq               Term        Total  loglift  logprob
term                                                                        
99    Default  1585.000000               body  1585.000000  30.0000  30.0000
445   Default  2829.000000              going  2829.000000  29.0000  29.0000
520   Default   857.000000              heart   857.000000  28.0000  28.0000
322   Default   701.000000             energy   701.000000  27.0000  27.0000
372   Default   930.000000               feel   930.000000  26.0000  26.0000
834   Default  2416.000000             people  2416.000000  25.0000  25.0000
1266  Default  2109.000000                way  2109.000000  24.0000  24.0000
633   Default   708.000000                let   708.000000  23.0000  23.0000
514   Default   464.000000               head   464.000000  22.0000  22.0000
462   Default  2688.000000                got  2688.000000  21.0000  21.0000
375   Default   366.000000            feeling   366.000000  20.0000  20.0000
442   Default   293.000000                god   293.000000  19.0000  19.0000
996   Default   270.000000               self   270.000000  18.0000  18.0000
1080  Default   478.000000              start   478.000000  17.0000  17.0000
955   Default  4461.000000              right  4461.000000  16.0000  16.0000
690   Default  1167.000000                lot  1167.000000  15.0000  15.0000
740   Default   405.000000               mind   405.000000  14.0000  14.0000
1227  Default   504.000000                use   504.000000  13.0000  13.0000
552   Default   271.000000              human   271.000000  12.0000  12.0000
67    Default   260.000000              balls   260.000000  11.0000  11.0000
255   Default   287.000000               deep   287.000000  10.0000  10.0000
376   Default   297.000000           feelings   297.000000   9.0000   9.0000
508   Default   364.000000            happens   364.000000   8.0000   8.0000
397   Default   183.000000             follow   183.000000   7.0000   7.0000
53    Default   363.000000         associated   363.000000   6.0000   6.0000
119   Default   242.000000            breathe   242.000000   5.0000   5.0000
122   Default   279.000000          breathing   279.000000   4.0000   4.0000
1011  Default   294.000000                sex   294.000000   3.0000   3.0000
1012  Default   235.000000             sexual   235.000000   2.0000   2.0000
669   Default   225.000000             listen   225.000000   1.0000   1.0000
...       ...          ...                ...          ...      ...      ...
428    Topic5     0.083607          generally    27.039422   1.5835  -7.2718
1304   Topic5     0.083608        world right    27.338332   1.5725  -7.2718
905    Topic5     0.083611    question friend    27.561148   1.5644  -7.2718
607    Topic5     0.083608         know maybe    27.663967   1.5607  -7.2718
964    Topic5     0.083608          right lot    27.693054   1.5596  -7.2718
1331   Topic5     0.083602    youtube channel    27.821050   1.5549  -7.2719
577    Topic5     0.083612           inviting    27.824716   1.5549  -7.2718
412    Topic5     0.083617         frustrated    27.833968   1.5547  -7.2717
1264   Topic5     0.083610    watching videos    27.918955   1.5515  -7.2718
805    Topic5     0.083616            opinion    28.037972   1.5473  -7.2717
138    Topic5     0.083610              bunch    28.092569   1.5453  -7.2718
1161   Topic5     0.083611        things know    28.479346   1.5317  -7.2718
573    Topic5     0.083606  interesting thing    28.582027   1.5280  -7.2718
397    Topic5     0.489816           

In [74]:
pyLDAvis.sklearn.prepare(lda, dtm_tf, tf_vectorizer, mds='tsne')

PreparedData(topic_coordinates=            Freq  cluster  topics           x           y
topic                                                    
2      54.667926        1       1  107.697790  174.786288
1      38.112405        1       2  -44.498161  121.170284
0       4.255031        1       3  118.258570 -153.443882
4       2.901172        1       4 -141.947323  -27.046107
3       0.063466        1       5 -208.990081  158.031109, topic_info=     Category         Freq               Term        Total  loglift  logprob
term                                                                        
99    Default  1585.000000               body  1585.000000  30.0000  30.0000
445   Default  2829.000000              going  2829.000000  29.0000  29.0000
520   Default   857.000000              heart   857.000000  28.0000  28.0000
322   Default   701.000000             energy   701.000000  27.0000  27.0000
372   Default   930.000000               feel   930.000000  26.0000  26.0000
834   Default  2416.000000             people  2416.000000  25.0000  25.0000
1266  Default  2109.000000                way  2109.000000  24.0000  24.0000
633   Default   708.000000                let   708.000000  23.0000  23.0000
514   Default   464.000000               head   464.000000  22.0000  22.0000
462   Default  2688.000000                got  2688.000000  21.0000  21.0000
375   Default   366.000000            feeling   366.000000  20.0000  20.0000
442   Default   293.000000                god   293.000000  19.0000  19.0000
996   Default   270.000000               self   270.000000  18.0000  18.0000
1080  Default   478.000000              start   478.000000  17.0000  17.0000
955   Default  4461.000000              right  4461.000000  16.0000  16.0000
690   Default  1167.000000                lot  1167.000000  15.0000  15.0000
740   Default   405.000000               mind   405.000000  14.0000  14.0000
1227  Default   504.000000                use   504.000000  13.0000  13.0000
552   Default   271.000000              human   271.000000  12.0000  12.0000
67    Default   260.000000              balls   260.000000  11.0000  11.0000
255   Default   287.000000               deep   287.000000  10.0000  10.0000
376   Default   297.000000           feelings   297.000000   9.0000   9.0000
508   Default   364.000000            happens   364.000000   8.0000   8.0000
397   Default   183.000000             follow   183.000000   7.0000   7.0000
53    Default   363.000000         associated   363.000000   6.0000   6.0000
119   Default   242.000000            breathe   242.000000   5.0000   5.0000
122   Default   279.000000          breathing   279.000000   4.0000   4.0000
1011  Default   294.000000                sex   294.000000   3.0000   3.0000
1012  Default   235.000000             sexual   235.000000   2.0000   2.0000
669   Default   225.000000             listen   225.000000   1.0000   1.0000
...       ...          ...                ...          ...      ...      ...
428    Topic5     0.083607          generally    27.039422   1.5835  -7.2718
1304   Topic5     0.083608        world right    27.338332   1.5725  -7.2718
905    Topic5     0.083611    question friend    27.561148   1.5644  -7.2718
607    Topic5     0.083608         know maybe    27.663967   1.5607  -7.2718
964    Topic5     0.083608          right lot    27.693054   1.5596  -7.2718
1331   Topic5     0.083602    youtube channel    27.821050   1.5549  -7.2719
577    Topic5     0.083612           inviting    27.824716   1.5549  -7.2718
412    Topic5     0.083617         frustrated    27.833968   1.5547  -7.2717
1264   Topic5     0.083610    watching videos    27.918955   1.5515  -7.2718
805    Topic5     0.083616            opinion    28.037972   1.5473  -7.2717
138    Topic5     0.083610              bunch    28.092569   1.5453  -7.2718
1161   Topic5     0.083611        things know    28.479346   1.5317  -7.2718
573    Topic5     0.083606  interesting thing    28.582027   1.5280  -7.2718
397    To

In [78]:
file_details = pickle_data["file_details"]

In [88]:
r = clf.transform(dtm_tf[0])

In [127]:
import numpy as np
r = np.array([[3,4,1,2,5]])
order = r.argsort()
ranks = order.argsort()
print(r)
print(order)
print(ranks)
print(order[0][-3:][::-1])

[[3 4 1 2 5]]
[[2 3 0 1 4]]
[[2 3 0 1 4]]
[4 1 0]


In [115]:
topics = []
for i, _ in enumerate(dtm_tf):
    r = clf.transform(dtm_tf[i])
    order = r.argsort()
    labels = order[0][-3:]
    topics.append((labels, file_details[i]))

In [128]:
for topic in topics:
    print(topic[0][::-1], topic[1])

[2 1 4] 3 Kinds Of People In Your Life-IyxeODanWJs.en.txt
[2 0 4] Sex With Other Women-kxCxD99XmdU.en.txt
[2 0 1] Escape THIS Malicious Psychological Trap-M4Ko32D5ALw.en.txt
[2 1 0] My boss is jerk, how do i tell him off-FVesOtzV32I.en.txt
[2 4 1] Save Yourself First-AtDDOO0ScGU.en.txt
[2 1 0] The Power of Doing Things You Hate-PODtipE3MHc.en.txt
[1 2 4] Selling Your Soul vs  Selling Juice-HHxkyyBqm-s.en.txt
[2 1 4] Sorry, I can't handle this (Leadership)-U4cXh8sdF9A.en.txt
[2 0 1] I only want virgins (who owns her vagina)-o2eOmAVxfZc.en.txt
[1 4 0] # Daily Habits of The Strong & Successful-F9WDR3pTYYo.en.txt
[2 1 0] Be More AGGRESSIVE!!-OPVWU6oSPZg.en.txt
[2 0 1] Easy Sex with Dumb Girls-mB246CSYqEU.en.txt
[1 2 0] Freedom to Do Whatever You Want-cTrjxhC4_SU.en.txt
[2 1 4] You MUST Promote Yourself-tfkj3pbLhvE.en.txt
[2 1 0] Redneck and a Muslim Hug-rhMM8ECJBHo.en.txt
[1 2 4] Cure Rigid Bodybuilder Syndrome-5O7ixEIPB04.en.txt
[2 0 4] Believe In YOURSELF - Rant Against Religion & Scienc

[2 1 0] The Art of Selfish Generosity-SYeNeDPrkQk.en.txt
[1 2 4] Reborn Through Battle Scars-3DmYrACkfj8.en.txt
[2 1 0] Go Fail, then Go Home-E_ghqZNdoqc.en.txt
[2 1 4] Nobody Respects Me-XBrn1ZxRI60.en.txt
[1 0 2] Best Fitness Books and Bogus Scientists (w_ Paul Chek)-gBPG7MqM6Fk.en.txt
[2 1 0] How To Get Your Passion Back-gPDzrg18q1w.en.txt
[2 1 0] When Is It Okay To FIGHT-0kwXQsbJvn4.en.txt
[2 1 4] How To Get Your Ex-Girlfriend Back-YjXK7zjTJLA.en.txt
[2 1 0] Create a Commanding Presence-EnNIPilEci0.en.txt
[2 1 4] Speak Up with Confidence-R-uwVYUmJt8.en.txt
[1 2 4] Make Him Do It Without Saying A Word-l6_EdU09vvI.en.txt
[1 2 4] What to do when everyone hates you-ifaPkMtkdi4.en.txt
[2 1 4] My Life is Great, But I'm Still Depressed-7AYxP2bTLlo.en.txt
[2 1 4] No Really Means Yes-r95yRi4GZPA.en.txt
[1 2 0] Get Hired and Never Be Fired-pmu2MGRBF1w.en.txt
[2 1 4] To be IN the World, but not OF it-CtOf5unCN2A.en.txt
[1 4 0] Bioenergetics For Your Face-e_wBaM4doN0.en.txt
[1 4 2] Fear of pub

[2 0 1] Being Vulnerable & Self Soothing-nLSMHqfu-_0.en.txt
[1 2 4] Conviction and Courage you can do ANYTHING!-imbFQMpFUvI.en.txt
[2 0 1] 24 year old virgin (fear vs pleasure)-_ZfdVc9jqSg.en.txt
[1 2 4] How to release trapped emotion speaking in tongues)-oNCuM08nZss.en.txt
[1 0 2] 5 Ways Training Saved My Life-0EpfRxL0PF4.en.txt
[2 1 0] Selling your Soul vs  Broken Heart-8WdkEzhpzCM.en.txt
[2 0 1] Stop Being So Awesome-de9RGVkEwuQ.en.txt
[1 2 4] Why I refer to myself in the 3rd person 'Elliott Hulse'-x7DqKj2kDO4.en.txt
[2 4 0] Truth About Your GUILT-kzx0gQdGnaA.en.txt
[2 1 4] Cheating on My Mean Wife-WaR7ltNrTbM.en.txt
[2 1 4] Save The Vagina-MQD8Y2lF4PM.en.txt
[2 1 0] Become More Attractive To Women-mxrP_yAceww.en.txt
[2 1 0] Stop Sucking Her Tits!-s_GVFUIq3UQ.en.txt
[1 0 2] Building 'Good Will' and Influence Is More Powerful Than Marketing [Yo Elliott Miami 2013]-s_WRb1Hqo8M.en.txt
[2 4 1] Ugly Girl-FvQsiWfv0Uc.en.txt
[1 2 4] Always Acting Fake-M5vUlYTGXhU.en.txt
[1 4 2] Train VIRTU

In [117]:
with open("topic_modelling_file_list.pickle", "wb") as f:
    pickle.dump(topics, f)